### PR TITLE
az_heat() improvements

### PR DESCRIPTION
**Pull request by Aariq**
This PR was originally a fix for #63, but I think that might have been mostly fixed by #62.  Now contains additional tests for `az_heat()` and some improvements in messages and how missing data for stations is handled.

This PR also adds a useful debug option I should have implemented a long time ago.  If you run `options(azmet.print_api_call = TRUE)` then you'll see the HTTP request printed for every `az_*()` function.  This will be helpful for debugging.  I'm not sure exactly where to document this (or even if it should be documented in a way that end users can see).

### CODE REVIEW

**Comment by Aariq** [comment]
@jeremylweiss if you could confirm that `az_heat()` is behaving as it should with this PR, that would be great!

**Review by jeremylweiss — APPROVED** [review]
This is nice progress. The confirmation of query and return dates through the messages is assuring, especially when requesting accumulations that start in the latter part of one calendar year and end in the early part of the next calendar year. As in dormancy/bud break models that look at either/both chill or/and heat accumulation.

I'm assuming that when date requests precede the earliest API availability date (currently "2023-01-01"), the new error message will appear once we merge that branch? Right now, `az_heat(start_date = "1980-01-01")` doesn't return `No data is available before 2021-01-01. Please choose a later date.`

**Comment by Aariq** [comment]
> I'm assuming that when date requests precede the earliest API availability date (currently "2023-01-01"), the new error message will appear once we merge that branch? Right now, `az_heat(start_date = "1980-01-01")` doesn't return `No data is available before 2021-01-01. Please choose a later date.`

I just merged `main` into this PR, so now it should work

```r
library(devtools)
load_all()
az_heat(start_date = "1980-01-01")
# Error in parse_params(station_id, start = start_date, end = end_date) : 
#   No data is available before 2021-01-01. Please choose a later date.

```

**Comment by jeremylweiss** [comment]
Yep, looks good from here, too! A nice confirmation that I was understanding the different branches and merges, phew! 🤣

**Pull request merged**
