### PR TITLE
Run `document()` to add help file for `az_15min()`

### PR DESCRIPTION
**Pull request by Aariq**
Looks like there was one missing piece of #72—I just ran `devtools::document()` to generate the help file for the new function.  It also updated the roxygen2 version in DESCRIPTION.

### CODE REVIEW

**Comment by Aariq** [comment]
Oh, and you should also remember to update NEWS.md at some point to mention the addition of the new function

**Comment by Aariq** [comment]
Checks are failing because of the links in the documentation to functions that don't exist yet.  I'll leave it up to you to decide whether to remove those for now, or just live with red x's until those get added.

**Comment by jeremylweiss** [comment]
> Oh, and you should also remember to update NEWS.md at some point to mention the addition of the new function

I'd bullet-point this under the "azmetr (development version)" section, right?

**Comment by Aariq** [comment]
> > Oh, and you should also remember to update NEWS.md at some point to mention the addition of the new function
> 
> I'd bullet-point this under the "azmetr (development version)" section, right?

Correct.  When you are ready to release a new version, you can use `usethis::use_version()` and it will automatically change this header to match the new version number and add a new (empty) development version section in NEWS.md.

**Comment by Aariq** [comment]
So, just to clarify, the workflow to use for documentation is to 1) edit the roxygen comments in the relevant .R file, 2) run `document()` to generate the .Rd file, 3) run `load_all()` and check the rendered version with `?az_15min`.  Repeat as necessary, but remember to run `document()` if you make more changes.

**Pull request merged**
